apps/funcionarios/urls.py
from django.urls import path, include
from .views import FuncionariosList, FuncionarioEdit, FuncionarioDelete, FuncionarioNovo
urlpatterns = [

    path('', FuncionariosList.as_view(), name='list_funcionarios'),
    path('editar/<int:pk>:', FuncionarioEdit.as_view(), name='update_funcionario'),
    path('delete/<int:pk>:', FuncionarioDelete.as_view(), name='delete_funcionario'),
    path('novo/', FuncionarioNovo.as_view(), name='create_funcionario'),
]

gestao_rh/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('apps.core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('empresas/', include('apps.empresas.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from apps.funcionarios.models import Funcionario
from django.shortcuts import reverse
# Create your models here.
class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.urls import reverse
from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa


# Create your models here.
class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('list_funcionarios')

    @property
    def total_horas_extra(self):
        total = self.registrohoraextra_set.filter(utilizada=False).aggregate(Sum('horas'))['horas__sum']
        return total or 0

apps/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


# Create your models here.
class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    utilizada = models.BooleanField(default=False)

    def __str__(self):
        return self.motivo

    def get_absolute_url(self):
        return reverse('list_hora_extra', args={self.funcionario.id})

apps/funcionarios/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from .models import Funcionario


# Create your views here.


class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username=funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1])
        funcionario.save()
        return super(FuncionarioNovo, self).form_valid(form)

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}
{% block title %} Formulario Empresa {% endblock title %}
{% block body %}
    <form method="post">
    {% csrf_token %}
        <h1>quer deletar {{obj}}</h1>
    <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>
{% endblock body %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %} Formulario Funcionario {% endblock title %}
{% block body %}
    <form method="post">
    {% csrf_token %}
    {{ form|bootstrap }}
    <button type="submit">Salvar</button>
    </form>
{% if object %}
<br>
<h2>Documentos</h2>
<ol>
{% for documento in object.documento_set.all %}

    <li><a href="{{ documento.arquivo.url }} "> {{ documento.descricao }}  </a></li>
{% endfor %}
    </ol>
<a href="{% url 'create_documento' object.id %}" class="btn btn-success">    Adicionar documento	</a>
<br>
<br>
<h2>Banco de Horas</h2>
<ol>
{% for registro_hora in object.registrohoraextra_set.all %}

    <li><a href="{% url 'update_hora_extra' registro_hora.id %}"> Motivo: {{ registro_hora.motivo }},  Quantidade de horas: {{ registro_hora.horas }}</li></a>
{% endfor %}
    <h3>Total Hora Extra {{object.total_horas_extra}}h</h3>
    <a href="{% url 'create_hora_extra'%}" class="btn btn-success"> Criar Hora Extra</a>
{%endif%}


{% endblock body %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}
{% block title %} Formulario Empresa {% endblock title %}
{% block body %}
    List

    {% for funcionario in object_list %}
    <br>
    <a href="{% url 'update_funcionario' funcionario.id %}">{{ funcionario }}</a>
    <a href="{% url 'delete_funcionario' funcionario.id %}">Delete</a>
    {% endfor %}
    <a href="{% url 'create_funcionario' %}" class="btn btn-info"> Novo </a>
{% endblock body %}